"""Validate hillshade implementation (gdaldem -igor).

The model is trained with hillshade generated by gdaldem -igor, which
produces overhead diffuse illumination (direction-agnostic cos(slope)).

These tests ensure:
1. The hillshade output is deterministic.
2. Igor hillshade is NOT aspect-sensitive (overhead illumination).
3. Output is valid uint8 with correct shape.
"""

import tempfile
from pathlib import Path

import numpy as np
import pytest
import rasterio
from rasterio.transform import Affine

from nationwide.processing import generate_hillshade

FIXTURES = Path(__file__).parent / "fixtures" / "hillshade"
DSM_DIR = FIXTURES / "dsm"

PATCH_NAMES = [
    "2581_1126_0_0.tif",
    "2586_1132_3_1.tif",
    "2640_1105_0_0.tif",
    "2780_1138_1_2.tif",
    "2593_1130_1_2.tif",
]


def _load_tif(path: Path) -> np.ndarray:
    with rasterio.open(path) as src:
        return src.read(1)


def _write_dsm(path: Path, data: np.ndarray, res: float = 0.5) -> None:
    """Write a numpy array as a single-band GeoTIFF with correct pixel size."""
    h, w = data.shape
    transform = Affine(res, 0, 0, 0, -res, h * res)
    with rasterio.open(
        path, "w", driver="GTiff",
        height=h, width=w, count=1,
        dtype=data.dtype, transform=transform,
    ) as dst:
        dst.write(data, 1)


@pytest.mark.parametrize("patch_name", PATCH_NAMES)
def test_hillshade_is_deterministic(patch_name):
    """Running hillshade twice on the same DSM produces identical output."""
    dsm_path = DSM_DIR / patch_name

    hs1 = generate_hillshade(dsm_path)
    hs2 = generate_hillshade(dsm_path)

    assert np.array_equal(hs1, hs2), "Hillshade should be deterministic"


def test_steep_slope_is_darker_than_flat():
    """Steeper terrain should produce lower hillshade values than flat terrain."""
    size = 50
    res = 0.5

    # Flat surface
    flat = np.full((size, size), 1000.0, dtype=np.float32)
    # Steep slope
    y_coords, x_coords = np.mgrid[0:size, 0:size]
    steep = (x_coords * 2.0).astype(np.float32)

    with tempfile.NamedTemporaryFile(suffix=".tif", delete=False) as f:
        flat_path = Path(f.name)
    with tempfile.NamedTemporaryFile(suffix=".tif", delete=False) as f:
        steep_path = Path(f.name)
    try:
        _write_dsm(flat_path, flat, res=res)
        _write_dsm(steep_path, steep, res=res)
        hs_flat = generate_hillshade(flat_path)
        hs_steep = generate_hillshade(steep_path)
    finally:
        flat_path.unlink(missing_ok=True)
        steep_path.unlink(missing_ok=True)

    flat_mean = float(hs_flat[10:-10, 10:-10].mean())
    steep_mean = float(hs_steep[10:-10, 10:-10].mean())
    assert flat_mean > steep_mean, (
        f"Flat ({flat_mean:.1f}) should be brighter than steep ({steep_mean:.1f})"
    )


@pytest.mark.parametrize("patch_name", PATCH_NAMES)
def test_hillshade_output_range(patch_name):
    """Hillshade output should be uint8 with values in a valid range."""
    dsm_path = DSM_DIR / patch_name

    hs = generate_hillshade(dsm_path)

    assert hs.dtype == np.uint8
    assert hs.max() <= 255
    assert hs.shape == _load_tif(dsm_path).shape


def test_flat_surface_is_bright():
    """A perfectly flat surface should produce maximum brightness with -igor."""
    size = 50
    dsm = np.full((size, size), 1000.0, dtype=np.float32)

    with tempfile.NamedTemporaryFile(suffix=".tif", delete=False) as f:
        dsm_path = Path(f.name)
    try:
        _write_dsm(dsm_path, dsm)
        hs = generate_hillshade(dsm_path)
    finally:
        dsm_path.unlink(missing_ok=True)

    center = hs[10:-10, 10:-10]
    assert center.mean() > 250, (
        f"Flat surface brightness {center.mean():.1f}, expected > 250"
    )
